### ISSUE TITLE
What is the "Theme Repository URL"?

### ISSUE THREAD

**Issue by solderjs** [julianoappelklein/hokus#42] opened 2020-02-28 05:22 UTC
I'm not really sure what I'm supposed to be doing to use this.

I downloaded the dmg, and it seemed like the only thing I could click on was "New" under "All Sites", so I clicked on that, and I got to this screen:

<img width="1172" alt="Screen Shot 2020-02-27 at 10 20 41 PM" src="https://user-images.githubusercontent.com/122831/75512696-7a0c5980-59af-11ea-96c1-cbc3855e150f.png">

But I can't hit "submit". I assume I need to enter "Theme Repository URL"... but I don't know what that means.

**Comment by julianoappelklein** [comment] 2020-02-28 13:06
@solderjs - the problem is not the Theme Repository URL, I think the problem is that the key only accepts numbers and lowercase letters.

There is a tip telling you that, but it vanishes as soon as you type something in the Key field. It's a bug.

**Comment by julianoappelklein** [comment] 2020-03-12 01:24
@solderjs - I'm closing this issue because there is another task addressing this problem: https://github.com/julianoappelklein/hokus/issues/21
Thank you!

**Closed by julianoappelklein** 2020-03-12 01:24 UTC

**Comment by igitur** [comment] 2021-04-09 07:14
Hi, I would also love to know what the Theme Repository URL is. Can you perhaps give some example URLs?
